"""What every artifact is.

Imports nothing, and that is load-bearing: if a document's dataclass lived in
the component that produces it, `cut` would import `boundaries` to read a
timeline, growing exactly the edges the file-handoff design removes. Every
component imports a shape from here; none imports another.

The split against the components is shape versus derivation --
`Timeline.index_at` is shape, `grid.enforce` is derivation.

These dataclasses are also the source for `db/json/*.schema.json`, generated by
`schemas.py` rather than maintained beside them.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass, field
from typing import Any, Optional

#: Rounding for identity and serialisation. Boundaries come from float
#: arithmetic over two independent clocks, so comparing them exactly would
#: report drift that is not there. A millisecond is far finer than any boundary
#: decision this pipeline makes.
PRECISION = 3


def _round(value: Optional[float]) -> Optional[float]:
    return None if value is None else round(value, PRECISION)


def _hash(payload: dict[str, Any]) -> str:
    """A short, stable hash of a document's identifying content.

    `sort_keys` is not cosmetic. `jsonb` preserves array order but not object
    key order -- it stores keys by (length, bytewise) -- so a document read back
    from Postgres hands back its keys in a different order from the file. A
    hash over iteration order would then differ by where the document was read
    from, which is a bug `falconvar` shipped and had to chase down.
    """
    text = json.dumps(payload, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(text.encode("utf-8")).hexdigest()[:16]


# --------------------------------------------------------------------------
# 1 · media  --  what the file is
# --------------------------------------------------------------------------

@dataclass(frozen=True)
class VideoStream:
    """How to open and address the picture.

    ``time_base`` is carried as a string ("1/12800") rather than a float:
    ``pts * time_base`` is exact rational arithmetic, and at timebases this
    fine a rounded float lands on the wrong frame. JSON has no rational type,
    so the exact form has to survive as text.
    """

    index: int
    codec: str
    rate: Optional[float]
    time_base: Optional[str]
    width: int
    height: int
    frames: Optional[int]
    duration_s: Optional[float]

    def as_dict(self) -> dict[str, Any]:
        return {"index": self.index, "codec": self.codec, "rate": self.rate,
                "time_base": self.time_base, "width": self.width,
                "height": self.height, "frames": self.frames,
                "duration_s": _round(self.duration_s)}

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> "VideoStream":
        return cls(index=d["index"], codec=d["codec"], rate=d.get("rate"),
                   time_base=d.get("time_base"), width=d["width"],
                   height=d["height"], frames=d.get("frames"),
                   duration_s=d.get("duration_s"))


@dataclass(frozen=True)
class AudioStream:
    """How to open the soundtrack. Deliberately not the waveform."""

    index: int
    codec: str
    rate: Optional[int]
    channels: Optional[int]
    duration_s: Optional[float]

    def as_dict(self) -> dict[str, Any]:
        return {"index": self.index, "codec": self.codec, "rate": self.rate,
                "channels": self.channels, "duration_s": _round(self.duration_s)}

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> "AudioStream":
        return cls(index=d["index"], codec=d["codec"], rate=d.get("rate"),
                   channels=d.get("channels"), duration_s=d.get("duration_s"))


@dataclass(frozen=True)
class Media:
    """One file, seen as the two streams it feeds.

    ``duration_s`` is the *container's*, and it is the one both halves must
    agree to use. The streams routinely disagree -- 205.280 s of video against
    205.264 s of audio on the reference file -- and a grid built from the
    shorter one leaves the tail of the longer outside every chunk.
    """

    video_id: str
    path: str
    container_format: str
    duration_s: Optional[float]
    video: Optional[VideoStream]
    audio: Optional[AudioStream]

    @property
    def has_video(self) -> bool:
        return self.video is not None

    @property
    def has_audio(self) -> bool:
        return self.audio is not None

    def as_dict(self) -> dict[str, Any]:
        return {
            "document": "media", "version": 1,
            "video_id": self.video_id,
            "path": self.path,
            "container_format": self.container_format,
            "duration_s": _round(self.duration_s),
            "video": self.video.as_dict() if self.video else None,
            "audio": self.audio.as_dict() if self.audio else None,
        }

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> "Media":
        return cls(
            video_id=d["video_id"], path=d["path"],
            container_format=d["container_format"],
            duration_s=d.get("duration_s"),
            video=VideoStream.from_dict(d["video"]) if d.get("video") else None,
            audio=AudioStream.from_dict(d["audio"]) if d.get("audio") else None,
        )


# --------------------------------------------------------------------------
# 2 · raw transcript  --  what was said, before any grid exists
# --------------------------------------------------------------------------

@dataclass
class RawTranscript:
    """Words, segments and speaker turns. **No chunks.**

    Stored before it is cut, and that is the asymmetry the whole ordering
    argument rests on. Whisper timestamps every word, so this can be re-cut to
    any grid, any number of times, without touching a model -- while a
    sampler's decisions are made during a decode pass and cannot be revisited.
    Keeping the ungridded record as a file is what lets a grid change without
    re-running inference; `falconvar` holds it in memory and discards it.

    ``turns`` is empty when no diarizer ran, and every segment then keeps
    ``speaker: None``. A transcript with no speaker information is truthful;
    one where everything is `SPEAKER_00` is not.
    """

    video_id: str
    model: dict[str, Any] = field(default_factory=dict)
    track: dict[str, Any] = field(default_factory=dict)
    segments: list[dict[str, Any]] = field(default_factory=list)
    words: list[dict[str, Any]] = field(default_factory=list)
    turns: list[dict[str, Any]] = field(default_factory=list)
    stats: dict[str, Any] = field(default_factory=dict)

    @property
    def speakers(self) -> list[str]:
        seen = {t.get("speaker") for t in self.turns}
        return sorted(s for s in seen if s)

    @property
    def silent(self) -> bool:
        return bool(self.track.get("silent", False))

    def as_dict(self) -> dict[str, Any]:
        return {
            "document": "raw_transcript", "version": 1,
            "video_id": self.video_id,
            "model": self.model,
            "track": self.track,
            "speakers": self.speakers,
            "segments": self.segments,
            "words": self.words,
            "turns": self.turns,
            "stats": self.stats,
        }

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> "RawTranscript":
        return cls(video_id=d["video_id"], model=d.get("model", {}),
                   track=d.get("track", {}), segments=d.get("segments", []),
                   words=d.get("words", []), turns=d.get("turns", []),
                   stats=d.get("stats", {}))


# --------------------------------------------------------------------------
# 3 · cuts  --  raw boundary evidence, before any guard
# --------------------------------------------------------------------------

@dataclass
class Cuts:
    """Interior cut times, plus the score series they were thresholded from.

    ``scores`` is the point of this document, not ``cuts``. A cut list is a
    *thresholding* of the series, so keeping the series makes re-thresholding
    arithmetic over a cached array instead of another pass over the video --
    the same expensive-half / cheap-half split `falconvar`'s calibrator uses
    for samplers: run the model once per frame, compare thousands of times.

    That matters most because the detector is strided. It scores the difference
    between *consecutive frames it was given*, so at stride 5 it compares
    moments 200 ms apart rather than 40 ms, and a threshold calibrated for
    adjacent frames fires far more often. Every real cut survives a stride;
    false positives are what rise. Caching the scores is what makes finding the
    new threshold free.
    """

    video_id: str
    source: str                      # "video" | "audio"
    detector: str                    # "content" | "vad" | "speaker"
    params: dict[str, Any] = field(default_factory=dict)
    cuts: list[float] = field(default_factory=list)
    scores: Optional[dict[str, Any]] = None
    stats: dict[str, Any] = field(default_factory=dict)

    def as_dict(self) -> dict[str, Any]:
        return {
            "document": "cuts", "version": 1,
            "video_id": self.video_id,
            "source": self.source,
            "detector": self.detector,
            "params": self.params,
            "cuts": [_round(c) for c in self.cuts],
            "scores": self.scores,
            "stats": self.stats,
        }

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> "Cuts":
        return cls(video_id=d["video_id"], source=d["source"],
                   detector=d["detector"], params=d.get("params", {}),
                   cuts=list(d.get("cuts", [])), scores=d.get("scores"),
                   stats=d.get("stats", {}))


# --------------------------------------------------------------------------
# 4 · timeline  --  THE GRID
# --------------------------------------------------------------------------

@dataclass
class Timeline:
    """Where every chunk starts and ends, and what decided it.

    `chunk_id` is the index into ``spans``, and it is a key three other
    documents inherit. A chunk is simultaneously the unit a describer
    summarises, the unit a transcript is cut into and the unit retrieval
    returns -- so if the picture and the soundtrack disagreed about where a
    boundary falls, one query would return two different clips with no honest
    way to say which is the answer.
    """

    video_id: str
    spans: list[tuple[float, float]]
    policy: str = "uniform"                       # uniform|scene|vad|speaker
    params: dict[str, Any] = field(default_factory=dict)
    #: "video", "audio", or "grid" when the policy is arithmetic and neither
    #: modality had to run. Recorded because a reader otherwise cannot tell a
    #: propagated boundary from a natively derived one.
    derived_from: str = "grid"

    def __len__(self) -> int:
        return len(self.spans)

    @property
    def duration_s(self) -> float:
        return self.spans[-1][1] if self.spans else 0.0

    def bounds_of(self, chunk_id: int) -> tuple[float, float]:
        """Start and end. Never an open end -- a supplied grid is complete, and
        that is the difference from a chunker deriving one as it streams."""
        return self.spans[chunk_id]

    def index_at(self, ts: float) -> Optional[int]:
        """Which chunk contains ``ts``. The last chunk owns its own end."""
        for index, (start, end) in enumerate(self.spans):
            if start <= ts < end:
                return index
        if self.spans and ts == self.spans[-1][1]:
            return len(self.spans) - 1
        return None

    def nearest(self, ts: float) -> int:
        """``index_at``, but never None.

        Media time outside the grid happens at the tail: the audio stream is
        routinely a few milliseconds shorter than the video one, so the last
        frames of a file can fall past a grid derived from the soundtrack. The
        nearest edge chunk owns them rather than the frame being dropped or a
        chunk being invented for it.
        """
        index = self.index_at(ts)
        if index is not None:
            return index
        if not self.spans:
            raise ValueError("an empty timeline contains no chunk")
        return 0 if ts < self.spans[0][0] else len(self.spans) - 1

    def fingerprint(self) -> str:
        """A hash of the grid and the policy that produced it.

        Every document cut on this grid records it. If two disagree, they were
        cut on different grids and `chunk_id` means two different things --
        which becomes a comparison a reader can make rather than a drift that
        nothing reports.
        """
        return _hash({
            "spans": [[_round(s), _round(e)] for s, e in self.spans],
            "policy": self.policy,
            "params": self.params,
        })

    def as_dict(self) -> dict[str, Any]:
        return {
            "document": "timeline", "version": 1,
            "video_id": self.video_id,
            "policy": self.policy,
            "derived_from": self.derived_from,
            "params": self.params,
            "fingerprint": self.fingerprint(),
            "duration_s": _round(self.duration_s),
            "chunk_count": len(self.spans),
            "chunks": [{"chunk_id": i, "start_ts": _round(s), "end_ts": _round(e)}
                       for i, (s, e) in enumerate(self.spans)],
        }

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> "Timeline":
        return cls(
            video_id=d["video_id"],
            spans=[(float(c["start_ts"]), float(c["end_ts"]))
                   for c in sorted(d["chunks"], key=lambda c: c["chunk_id"])],
            policy=d.get("policy", "uniform"),
            params=d.get("params", {}),
            derived_from=d.get("derived_from", "grid"),
        )


# --------------------------------------------------------------------------
# 5 · manifest  --  which frames were kept, why, and how to fetch them again
# --------------------------------------------------------------------------

@dataclass
class Manifest:
    """What each sampler kept from each chunk.

    **No `start_ts` / `end_ts`.** Those belong to the grid, and one copy of the
    grid is the whole point -- `falconvar` stores the spans in `video_chunks`
    *and* `audio_chunks` with nothing constraining them to agree. A reader
    joins on `chunk_id` and gets them from `timeline.json`.

    ``manifest_fingerprint`` is a hash of the source minus its uri, and the
    config minus the frame store. So it is known before the first chunk exists,
    survives the video and the store being moved, and changes when the sampling
    changes. Staleness downstream is a comparison against it, never a deletion:
    re-ingesting costs seconds where describing costs inference.
    """

    video_id: str
    timeline_fingerprint: str
    source: dict[str, Any] = field(default_factory=dict)
    config: dict[str, Any] = field(default_factory=dict)
    stats: dict[str, Any] = field(default_factory=dict)
    #: [{chunk_id, decimated_frames, samplers: {id: {frame_count, frames[]}}}]
    chunks: list[dict[str, Any]] = field(default_factory=list)

    def fingerprint(self) -> str:
        return _hash({
            "source": {k: v for k, v in self.source.items() if k != "path"},
            "config": {k: v for k, v in self.config.items()
                       if k != "frame_store"},
        })

    def sampler_ids(self) -> list[str]:
        return [s["id"] for s in self.config.get("samplers", [])]

    def frames_of(self, chunk_id: int, sampler_id: str) -> list[dict[str, Any]]:
        for chunk in self.chunks:
            if chunk["chunk_id"] == chunk_id:
                block = chunk.get("samplers", {}).get(sampler_id)
                return list(block["frames"]) if block else []
        return []

    def as_dict(self) -> dict[str, Any]:
        return {
            "document": "manifest", "version": 1,
            "video_id": self.video_id,
            "timeline_fingerprint": self.timeline_fingerprint,
            "manifest_fingerprint": self.fingerprint(),
            "source": self.source,
            "config": self.config,
            "stats": self.stats,
            "chunks": self.chunks,
        }

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> "Manifest":
        return cls(video_id=d["video_id"],
                   timeline_fingerprint=d.get("timeline_fingerprint", ""),
                   source=d.get("source", {}), config=d.get("config", {}),
                   stats=d.get("stats", {}), chunks=d.get("chunks", []))


# --------------------------------------------------------------------------
# 6 · transcript  --  what was said, on the grid
# --------------------------------------------------------------------------

@dataclass
class Transcript:
    """The raw transcript cut to chunks.

    **Chunks with no speech are kept, with empty text.** The grid is shared, so
    `chunk_id` must mean the same thing here as in the manifest; dropping the
    quiet ones renumbers everything after them and breaks that correspondence
    silently.

    Only `speakers` goes into `structured`, never `turns`. For a description
    the structured half is worth embedding because it holds what the summary
    does not; but `turns[].text` *is* the transcript, so rendering it would
    append the whole chunk a second time interleaved with timestamps read as
    numbers. The turns are the record and stay on the chunk.
    """

    video_id: str
    timeline_fingerprint: str = ""
    model: dict[str, Any] = field(default_factory=dict)
    chunks: list[dict[str, Any]] = field(default_factory=list)
    stats: dict[str, Any] = field(default_factory=dict)

    def text_of(self, chunk_id: int) -> str:
        for chunk in self.chunks:
            if chunk["chunk_id"] == chunk_id:
                return chunk.get("text", "")
        return ""

    def as_dict(self) -> dict[str, Any]:
        return {"document": "transcript", "version": 1,
                "video_id": self.video_id,
                "timeline_fingerprint": self.timeline_fingerprint,
                "model": self.model, "stats": self.stats,
                "chunks": self.chunks}

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> "Transcript":
        return cls(video_id=d["video_id"],
                   timeline_fingerprint=d.get("timeline_fingerprint", ""),
                   model=d.get("model", {}), chunks=d.get("chunks", []),
                   stats=d.get("stats", {}))


# --------------------------------------------------------------------------
# 7 · descriptions  --  one answer per (chunk, sampler)
# --------------------------------------------------------------------------

@dataclass
class Descriptions:
    """What a model said about each chunk, per sampler.

    Keyed by `sampler_id`, which for a pairing is `name:prompt` -- so
    `yolo:overview` and `clip:overview` stay distinct while asking one
    question. `model` carries a hash of the prompt module as well as the model
    id: editing a prompt changes the output but not the model name, and a
    resume that ignored it would report "10 skipped" having done nothing.
    """

    video_id: str
    timeline_fingerprint: str = ""
    manifest_fingerprint: str = ""
    model: dict[str, Any] = field(default_factory=dict)
    chunks: list[dict[str, Any]] = field(default_factory=list)
    stats: dict[str, Any] = field(default_factory=dict)

    def done(self) -> set[tuple[int, str]]:
        """Which (chunk, sampler) pairs already have an answer."""
        return {(c["chunk_id"], sid)
                for c in self.chunks for sid in c.get("samplers", {})}

    def as_dict(self) -> dict[str, Any]:
        return {"document": "descriptions", "version": 1,
                "video_id": self.video_id,
                "timeline_fingerprint": self.timeline_fingerprint,
                "manifest_fingerprint": self.manifest_fingerprint,
                "model": self.model, "stats": self.stats,
                "chunks": self.chunks}

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> "Descriptions":
        return cls(video_id=d["video_id"],
                   timeline_fingerprint=d.get("timeline_fingerprint", ""),
                   manifest_fingerprint=d.get("manifest_fingerprint", ""),
                   model=d.get("model", {}), chunks=d.get("chunks", []),
                   stats=d.get("stats", {}))


# --------------------------------------------------------------------------
# 8 · embedded  --  what text was embedded. For reading, not for searching.
# --------------------------------------------------------------------------

@dataclass
class Embedded:
    """Every unit's text, beside the hash that keys it.

    **No vectors.** This exists to be opened and read -- to see exactly what
    text a chunk contributed to the index -- and 1536 floats per unit is the
    part of that answer nobody can read. The vectors live in whichever real
    index the run wrote to.

    **One file per video, not per embedder.** `units.render()` produces the
    same text whichever model will embed it; only the vectors differ. A file
    per embedder would be several identical copies of the readable half.

    Written alongside the real index because the question it answers -- "what
    did this chunk actually contribute" -- is the one asked when a ranking
    looks wrong, and it is the measurement that established embedding the
    summary *and* the structured fields (0.705 against 0.528 MRR).
    """

    video_id: str
    timeline_fingerprint: str = ""
    units: list[dict[str, Any]] = field(default_factory=list)

    def text_of(self, chunk_id: int, sampler_id: str) -> str:
        for unit in self.units:
            if unit["chunk_id"] == chunk_id and unit["sampler_id"] == sampler_id:
                return unit.get("content", "")
        return ""

    def as_dict(self) -> dict[str, Any]:
        return {"document": "embedded", "version": 1,
                "video_id": self.video_id,
                "timeline_fingerprint": self.timeline_fingerprint,
                "count": len(self.units),
                "samplers": sorted({u["sampler_id"] for u in self.units}),
                "units": self.units}

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> "Embedded":
        return cls(video_id=d["video_id"],
                   timeline_fingerprint=d.get("timeline_fingerprint", ""),
                   units=d.get("units", []))


# --------------------------------------------------------------------------
# 9 · aggregate  --  video-level structure over what the chunks said
# --------------------------------------------------------------------------

@dataclass
class Aggregate:
    """One aggregator's answer about the whole video.

    ``inputs_fingerprint`` is a hash of the chunk text actually read. A summary
    of descriptions that have since been rewritten reads perfectly, which is
    precisely why staleness cannot be left to a reader to notice.
    """

    video_id: str
    aggregate_id: str
    tier: str
    payload: dict[str, Any] = field(default_factory=dict)
    inputs_fingerprint: str = ""
    stats: dict[str, Any] = field(default_factory=dict)

    def as_dict(self) -> dict[str, Any]:
        return {"document": "aggregate", "version": 1,
                "video_id": self.video_id, "aggregate_id": self.aggregate_id,
                "tier": self.tier, "inputs_fingerprint": self.inputs_fingerprint,
                "payload": self.payload, "stats": self.stats}

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> "Aggregate":
        return cls(video_id=d["video_id"], aggregate_id=d["aggregate_id"],
                   tier=d.get("tier", "free"), payload=d.get("payload", {}),
                   inputs_fingerprint=d.get("inputs_fingerprint", ""),
                   stats=d.get("stats", {}))


def fingerprint_of(payload: dict[str, Any]) -> str:
    """A stable hash of arbitrary content. Exposed for components that need
    their own staleness key -- `inputs_fingerprint`, `text_hash`."""
    return _hash(payload)


# --------------------------------------------------------------------------
# what every component hands back
# --------------------------------------------------------------------------

@dataclass
class Produced:
    """What a component actually wrote.

    A bare path would be shorter and say less. This reports the real output:
    no ``store`` on a run with the frame store off, no ``transcript`` on a
    silent file, and the stats a progress callback wants -- so a caller learns
    what happened rather than assuming from what it asked for.
    """

    video_id: str
    component: str
    backend: str                                  # "file" | "supabase" | both
    artifacts: dict[str, str] = field(default_factory=dict)
    stats: dict[str, Any] = field(default_factory=dict)
    skipped: list[str] = field(default_factory=list)

    def path(self, name: str) -> str:
        return self.artifacts[name]

    def as_dict(self) -> dict[str, Any]:
        return {"video_id": self.video_id, "component": self.component,
                "backend": self.backend, "artifacts": self.artifacts,
                "stats": self.stats, "skipped": self.skipped}


DOCUMENTS = {"media": Media, "raw_transcript": RawTranscript,
             "cuts": Cuts, "timeline": Timeline, "manifest": Manifest,
             "transcript": Transcript, "descriptions": Descriptions,
             "embedded": Embedded,
             "aggregate": Aggregate}

__all__ = ["PRECISION", "VideoStream", "AudioStream", "Media",
           "RawTranscript", "Cuts", "Timeline", "Manifest", "Transcript",
           "Descriptions", "Embedded", "Aggregate", "Produced", "fingerprint_of",
           "DOCUMENTS"]
